### ISSUE TITLE
`max-length` stopped working

### ISSUE THREAD

**Issue by ChaoticRoman** [sshnaidm/gpt-code-review-action#10]
I tried to use this action with my `OPENAI_API_TOKEN` that is supporting GPT-4 and longer context length:

https://github.com/ChaoticRoman/chatgpt-gui/blob/main/.github/workflows/code-review.yml

The features I implemented before that I remembered working does not work now, refusing to accept `max-length` parameter:

https://github.com/ChaoticRoman/chatgpt-gui/actions/runs/6668832660/job/18125283536#step:3:1

Let me investigate what is going on...

**Comment by sshnaidm** [comment]
Is it still the issue?

**Comment by ChaoticRoman** [comment]
[Tested](https://github.com/ChaoticRoman/chatgpt-gui/pull/16#issuecomment-1805593824) and it is working now, the release fixed the issue.
